include:
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-dom0.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-vm.yml'

variables:
  TRAVIS_INSTALL_EXCLUDE: "qubes-gui-dom0 qubes-audio-dom0"
  TRAVIS_INSTALL_EXCLUDE_DOM0: ""
