include:
- file: /common.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-vm.yml
  project: QubesOS/qubes-continuous-integration
variables:
  TRAVIS_INSTALL_EXCLUDE: qubes-gui-dom0 qubes-audio-dom0
  TRAVIS_INSTALL_EXCLUDE_DOM0: ''

lint:
  extends: .lint
  script:
    - black $BLACK_ARGS qubesguidaemon
